routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix'=>''],function(){
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('authors-customer', 'AuthorController@index')->name('authors.customer');
    Route::get('authors-show', 'AuthorController@anyDatatables')->name('datatable_author');
    
    Route::get('papers-customer', 'PaperController@index')->name('papers.customer');
    Route::get('papers-show', 'PaperController@anyDatatables')->name('datatable_papers');

    route::get('author-network', 'AuthorNetworkController@index')->name('author_network.index');
    route::get('author-network-customer', 'AuthorNetworkController@index')->name('author_network.customer');
    route::get('author-network/any-data', 'AuthorNetworkController@anyDatabase')->name('author_network.anyData');

    route::get('candidate', 'CandidateController@index')->name('candidate.index');
    route::get('candidate/any-data', 'CandidateController@anyDatabase')->name('candidate.anyData');

    route::get('candidate-customer', 'CandidateController@index')->name('candidate.customer');
});

Route::group(['prefix'=>'', 'middleware' => ['auth']],function(){
    Route::resource('authors', 'AuthorController');
    Route::get('authors-select', 'AuthorController@apiSelect')->name('select2_author');
    Route::get('compute-author-office', 'AuthorController@computeAuthorOffice')->name('computeAuthorOffice');

    Route::resource('papers', 'PaperController');
    Route::get('compute-keyword', 'PaperController@computeKeyword')->name('computeKeyword');

    Route::resource('users', 'UserController');

    route::get('author-network/update', 'AuthorNetworkController@computeNetwork')->name('author_network.update');
    
    route::get('candidate/update', 'CandidateController@computeCandidate')->name('candidate.update');
});



Route::group(['namespace'=>'Auth' ],function(){
    Route::get('login','LoginController@showLoginForm')->name('login');
    Route::post('login','LoginController@login');
    Route::get('logout','LoginController@logout');
    Route::post('logout','LoginController@logout')->name('logout');
    //reset password
    Route::get('password/reset','LoginController@getReset');
    Route::post('password/reset','LoginController@postReset');
});

resources/views/partials/nav.blade.php
<header class="main-header">
    <!-- Logo -->
    <a href="{{ route('home') }}" class="logo">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini"><b>A</b>LT</span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg"><b>Quản trị</b> website</span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>

        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                @if (!Auth::check())
                <li>
                    <a href="{{ route('login') }}">Đăng nhập</a>
                </li>
                @endif
                <!-- User Account: style can be found in dropdown.less -->
                <li class="dropdown user user-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <img src="{{ Auth::check() ?  asset(Auth::user()->image) :  asset('/images/256.png')  }}" class="user-image" alt="User Image">
                        <span class="hidden-xs">{{  Auth::check() ? Auth::user()->name : 'Khách'}}</span>
                    </a>
                    <ul class="dropdown-menu">
                        <!-- User image -->
                        <li class="user-header">
                            <img src="{{ Auth::check() ? asset(Auth::user()->image): '' }}" class="img-circle" alt="User Image">

                            <p>
                                {{ Auth::check() ? Auth::user()->name : 'Khách' }}
                                <small>{{ Auth::check() ? Auth::user()->email : 'Khách' }}</small>
                                <small>{{Auth::check() ? Auth::user()->phone : 'no phone'}}</small>
                            </p>
                        </li>
                        @if(Auth::check())
                        <!-- Menu Footer-->
                        <li class="user-footer">
                            <div class="pull-left">
                                <a href="#" class="btn btn-default btn-flat">Thông tin</a>
                            </div>

                            <div class="pull-right">
                                <a class="btn btn-default btn-flat" onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">Đăng suất</a>
                                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                    {{ csrf_field() }}
                                </form>
                            </div>
                        </li>
                        @endif
                    </ul>
                </li>
                <!-- Control Sidebar Toggle Button -->
            </ul>
        </div>
    </nav>
</header>

resources/views/partials/popup_delete.blade.php
<!-- Modal -->
<div class="modal fade" id="myModalDelete" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content_1">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Bạn có chắc chắn muốn xóa?</h4>
            </div>
            <form action="" class="submitDelete" method="post" >
                {!! csrf_field() !!}
                {{ method_field('DELETE') }}
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Đóng</button>
                    <button type="submit" class="btn btn-primary">Xóa</button>
                </div>
            </form>
        </div>
    </div>
</div>
 <script>
     function submitDelete(e) {
         var url = $(e).attr('href');
         console.log(url);
         $('.submitDelete').attr('action', url);
         return false;
     }
 </script>
<style>
    .modal-content_1 {
        background: #fff;
    }
</style>

resources/views/partials/slidebar.blade.php
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar user panel -->
        <div class="user-panel">
            <div class="pull-left image">
                <img src="{{ Auth::check() ? asset(Auth::user()->image): asset('/images/256.png') }}" class="img-circle" alt="User Image">
            </div>
            <div class="pull-left info">
                <p>{{ Auth::check() ? Auth::user()->name : 'Khách' }}</p>
                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>
        @if(Auth::check() && !\App\Entity\User::isMember(\Illuminate\Support\Facades\Auth::user()->role))
        <!-- sidebar menu: : style can be found in sidebar.less -->
            <ul class="sidebar-menu" data-widget="tree">
                <li class="header">Nội dung</li>
                <li class="{{ Request::is('authors', 'authors/create') ? 'active' : null }} treeview">
                    <a href="{{ route('authors.index') }}">
                        <i class="fa fa-user" aria-hidden="true"></i> <span>Quản lý tác giả</span>
                        <span class="pull-right-container">
                      <i class="fa fa-angle-left pull-right"></i>
                    </span>
                    </a>
                    <ul class="treeview-menu">
                        <li class="{{ Request::is( 'authors' ) ? 'active' : null }}">
                            <a href="{{ route('authors.index') }}"><i class="fa fa-circle-o"></i>Tất cả tác giả</a>
                        </li>
                        <li class="{{ Request::is('authors/cre
                        ate') ? 'active' : null }}">
                            <a href="{{ route('authors.create') }}"><i class="fa fa-circle-o"></i>Thêm mới tác giả</a>
                        </li>
                    </ul>
                </li>

                <li class="{{ Request::is('papers', 'papers/create') ? 'active' : null }} treeview">
                    <a href="{{ route('papers.index') }}">
                        <i class="fa fa-newspaper-o" aria-hidden="true"></i> <span>Quản lý tài liệu</span>
                        <span class="pull-right-container">
                      <i class="fa fa-angle-left pull-right"></i>
                    </span>
                    </a>
                    <ul class="treeview-menu">
                        <li class="{{ Request::is( 'papers' ) ? 'active' : null }}">
                            <a href="{{ route('papers.index') }}"><i class="fa fa-circle-o"></i>Tất cả tài liệu</a>
                        </li>
                        <li class="{{ Request::is('papers/cre
                        ate') ? 'active' : null }}">
                            <a href="{{ route('papers.create') }}"><i class="fa fa-circle-o"></i>Thêm mới tài liệu</a>
                        </li>
                    </ul>
                </li>
                <li class="{{ Request::is( route('author_network.index')) ? 'active' : null }} ">
                    <a href="{{ route('author_network.index') }}">
                        <i class="fa fa-link" aria-hidden="true"></i> <span>Quản lý mạng tác giả</span>
                    </a>
                </li>
                <li class="{{ Request::is( route('candidate.index')) ? 'active' : null }} ">
                    <a href="{{ route('candidate.index') }}">
                        <i class="fa fa-search" aria-hidden="true"></i> <span>Tìm kiếm ứng viên</span>
                    </a>
                </li>

                @if(\App\Entity\User::isManager(\Illuminate\Support\Facades\Auth::user()->role))
                    <li class="header">Thành viên</li>
                    <li class="{{ Request::is('admin/users', 'admin/users/create') ? 'active' : null }} treeview">
                        <a href="{{ route('users.index') }}">
                            <i class="fa fa-wrench" aria-hidden="true"></i> <span>Quản lý thành viên</span>
                            <span class="pull-right-container">
                      <i class="fa fa-angle-left pull-right"></i>
                    </span>
                        </a>
                        <ul class="treeview-menu">
                            <li class="{{ Request::is( 'admin/users' ) ? 'active' : null }}">
                                <a href="{{ route('users.index') }}"><i class="fa fa-circle-o"></i>Tất cả Thành viên</a>
                            </li>
                            <li class="{{ Request::is('admin/users/create') ? 'active' : null }}">
                                <a href="{{ route('users.create') }}"><i class="fa fa-circle-o"></i>Thêm mới thành viên</a>
                            </li>
                        </ul>
                    </li>
                @endif
            </ul>
            @else
                <ul class="sidebar-menu" data-widget="tree">
                    <li class="header">Nội dung</li>
                    <li class="{{ Request::is(route('authors.customer') ) ? 'active' : null }} ">
                        <a href="{{ route('authors.customer') }}">
                            <i class="fa fa-user" aria-hidden="true"></i> <span>Tra cứu tác giả</span>
                        </a>
                    </li>

                    <li class="{{ Request::is(route('papers.customer') ) ? 'active' : null }} ">
                        <a href="{{ route('papers.customer') }}">
                            <i class="fa fa-newspaper-o" aria-hidden="true"></i> <span>Tra cứu tài liệu</span>
                        </a>
                    </li>
                    <li class="{{ Request::is( route('author_network.customer')) ? 'active' : null }} ">
                        <a href="{{ route('author_network.customer') }}">
                            <i class="fa fa-link" aria-hidden="true"></i> <span>Tra cứu mạng tác giả</span>
                        </a>
                    </li>
                    <li class="{{ Request::is( route('candidate.customer')) ? 'active' : null }} ">
                        <a href="{{ route('candidate.customer') }}">
                            <i class="fa fa-search" aria-hidden="true"></i> <span>Tìm kiếm ứng viên</span>
                        </a>
                    </li>
                </ul>

        @endif
    </section>
    <!-- /.sidebar -->
</aside>