routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix'=>''],function(){
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('authors-customer', 'AuthorController@index')->name('authors.customer');
    Route::get('authors-show', 'AuthorController@anyDatatables')->name('datatable_author');
    
    Route::get('papers-customer', 'PaperController@index')->name('papers.customer');
    Route::get('papers-show', 'PaperController@anyDatatables')->name('datatable_papers');

    route::get('author-network', 'AuthorNetworkController@index')->name('author_network.index');
    route::get('author-network-customer', 'AuthorNetworkController@index')->name('author_network.customer');
    route::get('author-network/any-data', 'AuthorNetworkController@anyDatabase')->name('author_network.anyData');

    route::get('candidate', 'CandidateController@index')->name('candidate.index');
    route::get('candidate/any-data', 'CandidateController@anyDatabase')->name('candidate.anyData');

    route::get('candidate-customer', 'CandidateController@index')->name('candidate.customer');
});

Route::group(['prefix'=>'', 'middleware' => ['auth']],function(){
    Route::resource('authors', 'AuthorController');
    Route::get('authors-select', 'AuthorController@apiSelect')->name('select2_author');
    Route::get('compute-author-office', 'AuthorController@computeAuthorOffice')->name('computeAuthorOffice');

    Route::resource('papers', 'PaperController');
    Route::get('compute-keyword', 'PaperController@computeKeyword')->name('computeKeyword');

    Route::resource('users', 'UserController');

    route::get('author-network/update', 'AuthorNetworkController@computeNetwork')->name('author_network.update');
    
    route::get('candidate/update', 'CandidateController@computeCandidate')->name('candidate.update');
});



Route::group(['namespace'=>'Auth' ],function(){
    Route::get('login','LoginController@showLoginForm')->name('login');
    Route::post('login','LoginController@login');
    Route::get('logout','LoginController@logout');
    Route::post('logout','LoginController@logout')->name('logout');
    //reset password
    Route::get('password/reset','LoginController@getReset');
    Route::post('password/reset','LoginController@postReset');
});

resources/views/document/add.blade.php
@extends('layouts.app')

@section('content')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Thêm mới tài liệu
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="{{ route('papers.index') }}">Tài liệu</a></li>
            <li class="active">Thêm mới</li>
        </ol>
    </section>

    <section class="content">
        <div class="row">
            <!-- form start -->
            <form role="form" action="{{ route('papers.store') }}" method="POST">
                {!! csrf_field() !!}
                {{ method_field('POST') }}
                <div class="col-xs-12 col-md-12">

                    <!-- Nội dung thêm mới -->
                    <div class="box box-primary">
                        <div class="box-header with-border">
                            <h3 class="box-title">Nội dung</h3>
                        </div>
                        <!-- /.box-header -->

                        <div class="box-body">
                            <div class="form-group">
                                <label for="exampleInputEmail1">Chọn tên tác giả</label>
                                <select name="authors[]" class="form-control" id="author_list" multiple="multiple">

                                </select>
                            </div>

                            <div class="form-group">
                                <label for="exampleInputEmail1">Mã tài liệu</label>
                                <input type="text" class="form-control" name="id" placeholder="Mã tài liệu" required/>
                            </div>
                            
                            <div class="form-group">
                                <label for="exampleInputEmail1">Tiêu đề</label>
                                <input type="text" class="form-control" name="title" placeholder="Tiêu đề" />
                            </div>

                            <div class="form-group">
                                <label>Ngày xuất bản:</label>

                                <div class="input-group date">
                                    <div class="input-group-addon">
                                        <i class="fa fa-calendar"></i>
                                    </div>
                                    <input type="text" name="coverDate" class="form-control pull-right" id="datepicker">
                                </div>
                                <!-- /.input group -->
                            </div>

                            <div class="form-group">
                                <label for="exampleInputEmail1">Link trên trang khoa học</label>
                                <input type="text" class="form-control" name="url" placeholder="Đường dẫn..." >
                            </div>

                            <div class="form-group">
                                <label for="exampleInputEmail1">ID tạp chí</label>
                                <input type="text" class="form-control" name="issn" placeholder="ID tạp chí">
                            </div>

                            <div class="form-group">
                                <label for="exampleInputEmail1">Từ khóa</label>
                                <input type="text" class="form-control" name="keywords" placeholder="Từ khóa" >
                            </div>

                            <div class="form-group">
                                <label for="exampleInputEmail1">Abstract</label>
                                <input type="text" class="form-control" name="abstract" placeholder="Abstract" />
                            </div>

                            <div class="form-group" style="color: red;">
                                @if ($errors->has('title'))
                                    <label for="exampleInputEmail1">{{ $errors->first('title') }}</label>
                                @endif
                            </div>
                        </div>
                        <!-- /.box-body -->

                        <div class="box-footer">
                            <button type="submit" class="btn btn-primary">Thêm mới</button>
                        </div>
                    </div>
                    <!-- /.box -->
                </div>
                
            </form>
        </div>
    </section>
@endsection

resources/views/document/edit.blade.php
@extends('layouts.app')

@section('content')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Chỉnh sửa bài báo {{$paper->title}}
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="{{ route('papers.index') }}">Bài báo</a></li>
            <li class="active">Chỉnh sửa</li>
        </ol>
    </section>

    <section class="content">
        <div class="row">
            <!-- form start -->
            <form role="form" action="{{ route('papers.update', ['document_id' => $paper->document_id]) }}" method="POST">
                {!! csrf_field() !!}
                {{ method_field('PUT') }}
                <div class="col-xs-12 col-md-8">

                    <!-- Nội dung thêm mới -->
                    <div class="box box-primary">
                        <div class="box-header with-border">
                            <h3 class="box-title">Nội dung</h3>
                        </div>
                        <!-- /.box-header -->

                        <div class="box-body">

                            <div class="form-group">
                                <label for="exampleInputEmail1">Chọn tên tác giả</label>
                                <select name="authors[]" class="form-control" id="author_list" multiple="multiple">
                                     @foreach($authors as $author)
                                        <option value="{{ $author->id }}" selected>{{ $author->givenName }}</option>
                                     @endforeach
                                </select>
                            </div>

                            <div class="form-group">
                                <label for="exampleInputEmail1">Tiêu đề</label>
                                <input type="text" class="form-control" name="title" value="{{ $paper->title }}" placeholder="Tiêu đề" />
                            </div>

                            <div class="form-group">
                                <label>Ngày xuất bản:</label>

                                <div class="input-group date">
                                    <div class="input-group-addon">
                                        <i class="fa fa-calendar"></i>
                                    </div>
                                    <input type="text" name="coverDate" class="form-control pull-right" value="{{ $paper->coverDate }}" id="datepicker">
                                </div>
                                <!-- /.input group -->
                            </div>

                            <div class="form-group">
                                <label for="exampleInputEmail1">Link trên trang khoa học</label>
                                <input type="text" class="form-control" name="url" placeholder="Đường dẫn..." value="{{ $paper->url }}" >
                            </div>

                            <div class="form-group">
                                <label for="exampleInputEmail1">ID tạp chí</label>
                                <input type="text" class="form-control" name="issn" placeholder="ID tạp chí" value="{{ $paper->issn }}">
                            </div>

                            <div class="form-group">
                                <label for="exampleInputEmail1">Từ khóa</label>
                                <input type="text" class="form-control" name="keywords" placeholder="Từ khóa" value="{{ $paper->keywords }}">
                            </div>

                            <div class="form-group">
                                <label for="exampleInputEmail1">Abstract</label>
                                <textarea class="form-control" name="abstract">{{ $paper->abstract }}</textarea>
                            </div>

                            <div class="form-group" style="color: red;">
                                @if ($errors->has('title'))
                                    <label for="exampleInputEmail1">{{ $errors->first('title') }}</label>
                                @endif
                            </div>
                        </div>
                        <!-- /.box-body -->
                    </div>
                    <!-- /.box -->
                    
                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">Thay đổi</button>
                    </div>
                </div>
            </form>
        </div>
    </section>
@endsection

resources/views/document/list.blade.php
@extends('layouts.app')


@section('content')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Bài báo
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Bài báo</a></li>
            <li><a href="#">Danh sách bài báo</a></li>
        </ol>
    </section>
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        @if (Auth::check())
                        <a  href="{{ route('papers.create') }}"><button class="btn btn-primary">Thêm mới</button> </a>
                        <button class="btn btn-primary " onclick="return computeKeywords(this);" data-loading-text="Cập nhật...">Cập nhật keyword</button>
                        <div class="progress" style="display: none">
                            <div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" >
                                0%
                            </div>
                        </div>
                        @endif
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <table id="papers" class="table table-bordered table-striped">
                            <thead>
                            <tr>
                                <th width="5%">ID</th>
                                <th width="20%">Tiêu đề</th>
                                <th width="20%">Ngày xuất bản</th>
                                <th>Id tạp chí</th>
                                <th>Tác giả</th>
                                <th>keywords</th>
                                @if (Auth::check())
                                <th>Thao tác</th>
                                @endif
                            </tr>
                            </thead>
                        </table>
                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /.box -->
            </div>
        </div>
    </section>
     @include('partials.popup_delete')
@endsection

@push('scripts')
<script>
    $(function() {
        $('#papers').DataTable({
            processing: true,
            serverSide: true,
            ajax: '{!! route('datatable_papers') !!}',
            columns: [
                { data: 'id', name: 'id' },
                { data: 'title_show', name: 'title' },
                { data: 'coverDate', name: 'coverDate' },
                { data: 'issn', name: 'issn' },
                { data: 'author', name: 'author' },
                { data: 'keywords', name: 'keywords' },
                @if (Auth::check())
                { data: 'action', name: 'action', orderable: false, searchable: false },
                @endif
            ]
        });
    });

    function computeKeywords(e) {
        var btn = $(e).button('loading');
        $('.progress').show();
        var start = 0;
        update();
        function update() {
            $.ajax({
                type: "get",
                url: '{!! route('computeKeyword') !!}',
                data: {
                    start: start,
                },
                success: function(result){
                    var obj = jQuery.parseJSON( result);
                    $('.progress-bar').attr('style', 'width: '+obj.percent+'%;');
                    $('.progress-bar').empty();
                    $('.progress-bar').append(obj.percent+'%');
                    start += 100;
                    if (obj.success == 1) {
                        $('.progress-bar').attr('style', 'width: 100%;');
                        $('.progress-bar').empty();
                        $('.progress-bar').append('100%');
                        alert('Bạn đã cập nhật thành công');
                        btn.button('reset')
                        $('.progress').hide();
                    } else {
                        update();
                    }
                }
            });
        }
    }
</script>
@endpush