routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix'=>''],function(){
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('authors-customer', 'AuthorController@index')->name('authors.customer');
    Route::get('authors-show', 'AuthorController@anyDatatables')->name('datatable_author');
    
    Route::get('papers-customer', 'PaperController@index')->name('papers.customer');
    Route::get('papers-show', 'PaperController@anyDatatables')->name('datatable_papers');

    route::get('author-network', 'AuthorNetworkController@index')->name('author_network.index');
    route::get('author-network-customer', 'AuthorNetworkController@index')->name('author_network.customer');
    route::get('author-network/any-data', 'AuthorNetworkController@anyDatabase')->name('author_network.anyData');

    route::get('candidate', 'CandidateController@index')->name('candidate.index');
    route::get('candidate/any-data', 'CandidateController@anyDatabase')->name('candidate.anyData');

    route::get('candidate-customer', 'CandidateController@index')->name('candidate.customer');
});

Route::group(['prefix'=>'', 'middleware' => ['auth']],function(){
    Route::resource('authors', 'AuthorController');
    Route::get('authors-select', 'AuthorController@apiSelect')->name('select2_author');
    Route::get('compute-author-office', 'AuthorController@computeAuthorOffice')->name('computeAuthorOffice');

    Route::resource('papers', 'PaperController');
    Route::get('compute-keyword', 'PaperController@computeKeyword')->name('computeKeyword');

    Route::resource('users', 'UserController');

    route::get('author-network/update', 'AuthorNetworkController@computeNetwork')->name('author_network.update');
    
    route::get('candidate/update', 'CandidateController@computeCandidate')->name('candidate.update');
});



Route::group(['namespace'=>'Auth' ],function(){
    Route::get('login','LoginController@showLoginForm')->name('login');
    Route::post('login','LoginController@login');
    Route::get('logout','LoginController@logout');
    Route::post('logout','LoginController@logout')->name('logout');
    //reset password
    Route::get('password/reset','LoginController@getReset');
    Route::post('password/reset','LoginController@postReset');
});

app/Http/Controllers/AuthorController.php
<?php

namespace App\Http\Controllers;

use App\Entity\Author;
use App\Entity\AuthorOffice;
use App\Entity\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Yajra\Datatables\Datatables;
use Illuminate\Validation\Rule;
use Validator;

class AuthorController extends LayoutController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('author.list');
    }

    
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('author.add');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validation = Validator::make($request->all(), [
            'givenName' => 'required',
            'email' => 'required|email',
        ]);

        // if validation fail return error
        if ($validation->fails()) {
            return redirect('authors/create')
                ->withErrors($validation)
                ->withInput();
        }

        $author = Author();
        $author->insert([
            'givenName' => $request->input('givenName'),
            'surname' => $request->input('surname'),
            'email' => $request->input('email'),
            'affiliation' => $request->input('affiliation'),
            'subjects' => $request->input('subjects'),
            'url' => $request->input('url'),
            'created_at' => new \Datetime(),
            'id' => $request->input('id'),

        ]);

        return redirect(route('authors.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Entity\Author  $author
     * @return \Illuminate\Http\Response
     */
    public function show(Author $author)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Entity\Author  $author
     * @return \Illuminate\Http\Response
     */
    public function edit(Author $author)
    {
        return view('author.edit', compact('author'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Entity\Author  $author
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Author $author)
    {
        $validation = Validator::make($request->all(), [
            'givenName' => 'required',
            'email' => 'required|email',
        ]);

        // if validation fail return error
        if ($validation->fails()) {
            return redirect(route('authors.edit', ['author_id' => $author->author_id]))
                ->withErrors($validation)
                ->withInput();
        }

        $author->update([
            'givenName' => $request->input('givenName'),
            'surname' => $request->input('surname'),
            'email' => $request->input('email'),
            'affiliation' => $request->input('affiliation'),
            'subjects' => $request->input('subjects'),
            'url' => $request->input('url'),
            'created_at' => new \Datetime(),
            'id' => $request->input('id'),

        ]);

        return redirect(route('authors.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Entity\Author  $author
     * @return \Illuminate\Http\Response
     */
    public function destroy(Author $author)
    {
        $author->delete();

        return redirect(route('authors.index'));
    }

    public function anyDatatables() {
        $author = new Author();
        $authors = $author->select('*');
        
        return Datatables::of($authors)
            ->addColumn('action', function($author) {
                if (!Auth::check()) {
                    return '';
                }
                $string =  '<a href="'.route('authors.edit', ['author_id' => $author->author_id]).'">
                           <button class="btn btn-primary"><i class="fa fa-pencil" aria-hidden="true"></i></button>
                       </a>';
                $string .= '<a  href="'.route('authors.destroy', ['author_id' => $author->author_id]).'" class="btn btn-danger btnDelete" 
                            data-toggle="modal" data-target="#myModalDelete" onclick="return submitDelete(this);">
                               <i class="fa fa-trash-o" aria-hidden="true"></i>
                            </a>';
                return $string;
            })
            ->addColumn('title_show', function($author) {
                $string = '<a href="'.$author->url.'">'.$author->surname.'('.$author->givenName.')</a>';

                return $string;
            })
            ->rawColumns(['action', 'title_show'])
            ->make(true);
    }

    public function apiSelect(Request $request) {
        $input = $request->input('search');
        $authors = Author::where('givenName', 'like', $input.'%')
            ->orWhere('givenName', 'like', '%'.$input.'%')
            ->orWhere('surname', 'like', '% '.$input.'%')
            ->orWhere('surname', 'like', $input.'%')
            ->get( ['givenName AS text', 'id'])->toArray();
        
        if (!empty($input))
        {
            return response()->json([
                'results' => $authors
            ])->header('Content-Type', 'text/plain');
        }
        else
        {
            return response()->json([
                'results' => ''
            ])->header('Content-Type', 'text/plain');
        }
    }

    public function computeAuthorOffice(Request $request) {
        $start = $request->input('start');
        if ($start == 0) {
            $authorOffice = new AuthorOffice();
            $authorOffice->truncate();
        }
        $limit = 100;
        // Số lượng tác giả chạy
        //$countPaper =  Author::orderBy('author_id', 'asc')->count();
        $countAuthor = 200;

        $authors =  Author::orderBy('author_id', 'asc')->offset($start)
            ->limit($limit)->get();
        
        if (empty($authors) || ($start >= $countAuthor) ) {
            return response([
                'status' => 200,
                'success' =>  1,
                'percent' => 100
            ])->header('Content-Type', 'text/plain');
        }

        $insertData = array();
        foreach ($authors as $author) {
            $areas = explode(',', $author->affiliation);
            if (count($areas) == 3) {
                $insertData[] = [
                    'author_id' => $author->id,
                    'university' =>  $areas[0],
                    'department' =>  '',
                    'province' => $areas[1],
                    'country' =>  $areas[2],
                ];
            }

            if (count($areas) == 4) {
                $insertData[] = [
                    'author_id' => $author->id,
                    'university' =>  $areas[0],
                    'department' => $areas[1] ,
                    'province' => $areas[2],
                    'country' =>  $areas[3],
                ];
            }

            if (count($areas) == 5) {
                $insertData[] = [
                    'author_id' => $author->id,
                    'university' =>  $areas[0],
                    'department' => $areas[1].', '.$areas[2] ,
                    'province' => $areas[3],
                    'country' =>  $areas[4],
                ];
            }
        }

        $authorOffice = new AuthorOffice();
        $authorOffice->insert($insertData);

        return response([
            'status' => 200,
            'success' => 0,
            'percent' => ($start/$countAuthor)*100
        ])->header('Content-Type', 'text/plain');

    }
}

resources/views/author/add.blade.php
@extends('layouts.app')

@section('content')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Thêm mới tác giả
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="{{ route('authors.index') }}">Tác giả</a></li>
            <li class="active">Thêm mới</li>
        </ol>
    </section>

    <section class="content">
        <div class="row">
            <!-- form start -->
            <form role="form" action="{{ route('authors.store') }}" method="POST">
                {!! csrf_field() !!}
                {{ method_field('POST') }}
                <div class="col-xs-12 col-md-12">

                    <!-- Nội dung thêm mới -->
                    <div class="box box-primary">
                        <div class="box-header with-border">
                            <h3 class="box-title">Nội dung</h3>
                        </div>
                        <!-- /.box-header -->

                        <div class="box-body">

                            <div class="form-group">
                                <label for="exampleInputEmail1">Mã tác giả</label>
                                <input type="text" class="form-control" name="id" placeholder="Mã tác giả" >
                            </div>
                            
                            <div class="form-group">
                                <label for="exampleInputEmail1">Trường/viện nơi họ làm việc</label>
                                <input type="text" class="form-control" name="affiliation" placeholder="Trường/viện nơi họ làm việc" >
                            </div>

                            <div class="form-group">
                                <label for="exampleInputEmail1">Lĩnh vực chuyên môn</label>
                                <input type="text" class="form-control" name="subjects" placeholder="Lĩnh vực chuyên môn" >
                            </div>

                            <div class="form-group">
                                <label for="exampleInputEmail1">Tên chính thức</label>
                                <input type="text" class="form-control" name="givenName" placeholder="Tên chính thức" required>
                            </div>

                            <div class="form-group">
                                <label for="exampleInputEmail1">Ký danh</label>
                                <input type="text" class="form-control" name="surname" placeholder="Ký danh" >
                            </div>

                            <div class="form-group">
                                <label for="exampleInputEmail1">Email</label>
                                <input type="email" class="form-control" name="email" placeholder="Email" required />
                            </div>

                            <div class="form-group">
                                <label for="exampleInputEmail1">Trang cá nhân</label>
                                <input type="text" class="form-control" name="url" placeholder="Trang cá nhân" >
                            </div>

                            <div class="form-group" style="color: red;">
                                @if ($errors->has('email'))
                                    <label for="exampleInputEmail1">{{ $errors->first('email') }}</label>
                                @endif
                                    @if ($errors->has('givenName'))
                                        <label for="exampleInputEmail1">{{ $errors->first('givenName') }}</label>
                                    @endif
                            </div>
                        </div>
                        <!-- /.box-body -->

                        <div class="box-footer">
                            <button type="submit" class="btn btn-primary">Thêm mới</button>
                        </div>
                    </div>
                    <!-- /.box -->
                </div>
                
            </form>
        </div>
    </section>
@endsection

resources/views/author/edit.blade.php
@extends('layouts.app')

@section('content')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Chỉnh sửa tác giả {{$author->givenName}} ({{$author->surname}})
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="{{ route('authors.index') }}">Tác giả</a></li>
            <li class="active">Chỉnh sửa</li>
        </ol>
    </section>

    <section class="content">
        <div class="row">
            <!-- form start -->
            <form role="form" action="{{ route('authors.update', ['author_id' => $author->author_id]) }}" method="POST">
                {!! csrf_field() !!}
                {{ method_field('PUT') }}
                <div class="col-xs-12 col-md-8">

                    <!-- Nội dung thêm mới -->
                    <div class="box box-primary">
                        <div class="box-header with-border">
                            <h3 class="box-title">Nội dung</h3>
                        </div>
                        <!-- /.box-header -->

                        <div class="box-body">
                            <div class="form-group">
                                <label for="exampleInputEmail1">Mã tác giả</label>
                                <input type="text" class="form-control" value="{{ $author->id }}" name="id" placeholder="Mã tác giả" required>
                            </div>

                            <div class="form-group">
                                <label for="exampleInputEmail1">Trường/viện nơi họ làm việc</label>
                                <input type="text" class="form-control" value="{{ $author->affiliation }}" name="affiliation" placeholder="Trường/viện nơi họ làm việc" >
                            </div>


                            <div class="form-group">
                                <label for="exampleInputEmail1">Lĩnh vực chuyên môn</label>
                                <input type="text" class="form-control"  value="{{ $author->subjects }}" name="subjects" placeholder="Lĩnh vực chuyên môn" >
                            </div>

                            <div class="form-group">
                                <label for="exampleInputEmail1">Tên chính thức</label>
                                <input type="text" class="form-control" value="{{ $author->givenName }}" name="givenName" placeholder="Tên chính thức" required>
                            </div>

                            <div class="form-group">
                                <label for="exampleInputEmail1">Ký danh</label>
                                <input type="text" class="form-control" value="{{ $author->surname }}" name="surname" placeholder="Ký danh" >
                            </div>

                            <div class="form-group">
                                <label for="exampleInputEmail1">Email</label>
                                <input type="email" class="form-control" value="{{ $author->email }}" name="email" placeholder="Email" required />
                            </div>

                            <div class="form-group">
                                <label for="exampleInputEmail1">Trang cá nhân</label>
                                <input type="text" class="form-control" value="{{ $author->url }}" name="url" placeholder="Trang cá nhân" >
                            </div>

                            <div class="form-group" style="color: red;">
                                @if ($errors->has('email'))
                                    <label for="exampleInputEmail1">{{ $errors->first('email') }}</label>
                                @endif
                                @if ($errors->has('givenName'))
                                    <label for="exampleInputEmail1">{{ $errors->first('givenName') }}</label>
                                @endif
                            </div>
                        </div>
                        <!-- /.box-body -->
                    </div>
                    <!-- /.box -->
                    
                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">Thay đổi</button>
                    </div>
                </div>
            </form>
        </div>
    </section>
@endsection

resources/views/author/list.blade.php
@extends('layouts.app')


@section('content')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Tác giả
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">Danh sách tác giả</a></li>
        </ol>
    </section>
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        @if (Auth::check())
                        <a  href="{{ route('authors.create') }}"><button class="btn btn-primary">Thêm mới</button> </a>
                        <button class="btn btn-primary " onclick="return computeAuthorOffice(this);" data-loading-text="Cập nhật...">Cập nhật Phòng ban làm việc</button>
                        <div class="progress" style="display: none">
                            <div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" >
                                0%
                            </div>
                        </div>
                        @endif
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <table id="authors" class="table table-bordered table-striped">
                            <thead>
                            <tr>
                                <th width="5%">ID</th>
                                <th width="10%">Tên </th>
                                <th width="10%">Email</th>
                                <th width="20%">Nơi làm việc</th>
                                <th width="20%">Lĩnh vực chuyên môn</th>
                                @if (Auth::check())
                                    <th>Thao tác</th>
                                @endif
                            </tr>
                            </thead>
                        </table>
                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /.box -->
            </div>
        </div>
    </section>
     @include('partials.popup_delete')
@endsection

@push('scripts')
<script>
    $(function() {
        $('#authors').DataTable({
            processing: true,
            serverSide: true,
            ajax: '{!! route('datatable_author') !!}',
            columns: [
                { data: 'id', name: 'id' },
                { data: 'title_show', name: 'givenName' },
                { data: 'email', name: 'email' },
                { data: 'affiliation', name: 'affiliation' },
                { data: 'subjects', name: 'subjects' },
                @if (Auth::check())
                { data: 'action', name: 'action', orderable: false, searchable: false },
                @endif
            ]
        });
    });

    function computeAuthorOffice(e) {
        var btn = $(e).button('loading');
        $('.progress').show();
        var start = 0;
        update();
        function update() {
            $.ajax({
                type: "get",
                url: '{!! route('computeAuthorOffice') !!}',
                data: {
                    start: start,
                },
                success: function(result){
                    var obj = jQuery.parseJSON( result);
                    console.log(start);
                    $('.progress-bar').attr('style', 'width: '+obj.percent+'%;');
                    $('.progress-bar').empty();
                    $('.progress-bar').append(obj.percent+'%');
                    start += 100;
                    if (obj.success == 1) {
                        $('.progress-bar').attr('style', 'width: 100%;');
                        $('.progress-bar').empty();
                        $('.progress-bar').append('100%');
                        alert('Bạn đã cập nhật thành công');
                        btn.button('reset')
                        $('.progress').hide();
                    } else {
                        update();
                    }
                }
            });
        }
    }
</script>
@endpush